server:
  port: 8081
  servlet:
    context-path: /csiqi
    session:
      timeout: 1800s
      #jsp热部署
    jsp:
      init-parameters:
        development: true
spring:
  session:
      store-type: redis
      timeout: 1800s
      redis:
        flush-mode: on_save
        namespace: spring:session
  redis:
      #password: JiLiG087Z
      host: 127.0.0.1
      port: 6379
      timeout: 10000ms
  jedis:
        pool:
          # 最大空闲连接数
          max-idle: 500
          # 最小空闲连接数
          min-idle: 50
          # 等待可用连接的最大时间，负数为不限制
          max-wait:  -1s
          # 最大活跃连接数，负数为不限制
          max-active: -1
  datasource:
    name: ideadb
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/ideadb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  output:
    ansi:
      # 日志着色功能
      enabled: DETECT
  thymeleaf:
    prefix:
     classpath: /templates/
# 禁用 thymeleaf 缓存 未见上传配置
    cache: false
    mode: HTML5
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  mvc:
    static-path-pattern: /static/**
# 热部署
  devtools:
     restart:
       enabled: true
       additional-exclude: WEB-INF/**
  # 是否支持批量上传   (默认值 true)
  servlet:
     multipart:
      enabled: true
  # 上传文件的临时目录 （一般情况下不用特意修改）
      location: E:\ideaWorkSpace\uploadImg
  # 上传文件最大为 1M （默认值 1M 根据自身业务自行控制即可）
      max-file-size: 1048576
  # 上传请求最大为 10M（默认值10M 根据自身业务自行控制即可）
      max-request-size: 10485760
  # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0
  # 判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）
      resolve-lazily: false
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.csiqi.model  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check



logging:
  level:
    com.csiqi: DEBUG
  file: ./csiqi/logs/core.log
  root: INFO
